name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 构建和部署文档
  deploy-docs:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build docs
      run: npm run build --workspace=packages/docs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/docs/dist
        destination_dir: docs

  # 构建和部署 Storybook
  deploy-storybook:
    runs-on: ubuntu-latest
    name: Deploy Storybook
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Storybook
      run: npm run build-storybook --workspace=packages/client
    
    - name: Deploy Storybook to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/client/storybook-static
        destination_dir: storybook

  # 构建 Docker 镜像
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/koa-html-template:latest
          ${{ secrets.DOCKER_USERNAME }}/koa-html-template:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 